alter table coment_task drop constraint FKlwhs34s6ems1ciko0p5qyp03w;
alter table coment_task drop constraint FKa3voby7ppkwporapfe47ltl27;
alter table inform_user_coment drop constraint FKl9c189233wodsa51p9e4y6vk0;
alter table inform_user_coment drop constraint FKp7m6u0olidslu8h4hkqb12or0;
alter table link_stage_proect drop constraint FKqbjt65fph8gox43sgdqt4a5mk;
alter table link_stage_proect drop constraint FKck7er41uc1rqc28wixj6d3koc;
alter table proect drop constraint FKsbj6w06ypup2wvadxognknla5;
alter table stages_proect drop constraint FKqkas84kc2c0syh5e3xh1nsoh4;
alter table stages_proect drop constraint FKi5t0cbd3x8cyphljycdvhq16l;
alter table task_user drop constraint FK7w9foy29vk0w6t9nafmhqcm3u;
alter table task_user drop constraint FKhgreb8w3xhjqs73nvb6w495ao;
alter table tasktab drop constraint FKfp20nqitj9xb4cf0c19kf3dkl;
alter table tasktab drop constraint FKpmalev9ukipjd21jb6yh96qvi;
alter table tasktab drop constraint FK9qjbdaogu1haa1jhcb34gf9yr;
alter table User_Role drop constraint FK3tdtqg65e5n3wvj1w2lga3r;
alter table User_Role drop constraint FKiifkjb98bm76mqc1p6lmibs5o;
alter table users_proect drop constraint FKbedjskyxhg3gjgaomm98n9r1p;
alter table users_proect drop constraint FKra0o7ico2n0ikob3os5lq3dqh;
alter table users_proect drop constraint FKnfdqf22iwfdukqcglqxy0grpl;
drop table if exists App_Role cascade;
drop table if exists app_user cascade;
drop table if exists coment_task cascade;
drop table if exists inform_user_coment cascade;
drop table if exists link_stage_proect cascade;
drop table if exists proect cascade;
drop table if exists project_positions cascade;
drop table if exists stages_proect cascade;
drop table if exists statetask cascade;
drop table if exists task_user cascade;
drop table if exists tasktab cascade;
drop table if exists typetask cascade;
drop table if exists User_Role cascade;
drop table if exists users_proect cascade;
drop sequence if exists customer_approle;
drop sequence if exists customer_appuser;
drop sequence if exists customer_comenttask;
drop sequence if exists customer_inf_user_coment;
drop sequence if exists customer_link_stage_proect;
drop sequence if exists customer_proect;
drop sequence if exists customer_project_position;
drop sequence if exists customer_stages_proect;
drop sequence if exists customer_state_task;
drop sequence if exists customer_task_user;
drop sequence if exists customer_tasktab;
drop sequence if exists customer_type_task;
drop sequence if exists customer_user_proect;
drop sequence if exists customer_userrole;
create sequence customer_approle start 1 increment 1;
create sequence customer_appuser start 1 increment 1;
create sequence customer_comenttask start 1 increment 1;
create sequence customer_inf_user_coment start 1 increment 1;
create sequence customer_link_stage_proect start 1 increment 1;
create sequence customer_proect start 1 increment 1;
create sequence customer_project_position start 1 increment 1;
create sequence customer_stages_proect start 1 increment 1;
create sequence customer_state_task start 1 increment 1;
create sequence customer_task_user start 1 increment 1;
create sequence customer_tasktab start 1 increment 1;
create sequence customer_type_task start 1 increment 1;
create sequence customer_user_proect start 1 increment 1;
create sequence customer_userrole start 1 increment 1;
create table App_Role (Role_Id int8 not null, Role_Name varchar(30) not null, primary key (Role_Id));
create table app_user (user_id int8 not null, enabled int4 not null, encryted_password varchar(255) not null, user_name varchar(255) not null, primary key (user_id));
create table coment_task (id int8 not null, countsled int4, datecoment date, textcoment varchar(255), idtask int8, usercoment int8, primary key (id));
create table inform_user_coment (id int8 not null, text varchar(255), idtask int8, iduser int8, primary key (id));
create table link_stage_proect (id int8 not null, idstage int8, idtask int8, primary key (id));
create table proect (id int8 not null, dateend timestamp, daterun timestamp, description varchar(255), name varchar(255), readiness int4, idsost int8, primary key (id));
create table project_positions (id int8 not null, name varchar(255), primary key (id));
create table stages_proect (id int8 not null, dateend timestamp, daterun timestamp, description varchar(255), name varchar(255), readiness int4, idproect int8, idsost int8, primary key (id));
create table statetask (id int8 not null, name varchar(255) not null, primary key (id));
create table task_user (id int8 not null, idtask int8, iduser int8, primary key (id));
create table tasktab (id int8 not null, description varchar(255), enddate timestamp, evaluation float8, modeldate timestamp, name varchar(255), startdate timestamp, directortask int8, state int8, typetask int8, primary key (id));
create table typetask (id int8 not null, name varchar(255) not null, primary key (id));
create table User_Role (Id int8 not null, Role_Id int8, User_Id int8, primary key (Id));
create table users_proect (id int8 not null, idposition int8, idproect int8, iduser int8, primary key (id));
alter table App_Role add constraint APP_ROLE_UK unique (Role_Name);
alter table User_Role add constraint USER_ROLE_UK unique (User_Id, Role_Id);
alter table coment_task add constraint FKlwhs34s6ems1ciko0p5qyp03w foreign key (idtask) references tasktab;
alter table coment_task add constraint FKa3voby7ppkwporapfe47ltl27 foreign key (usercoment) references app_user;
alter table inform_user_coment add constraint FKl9c189233wodsa51p9e4y6vk0 foreign key (idtask) references coment_task;
alter table inform_user_coment add constraint FKp7m6u0olidslu8h4hkqb12or0 foreign key (iduser) references app_user;
alter table link_stage_proect add constraint FKqbjt65fph8gox43sgdqt4a5mk foreign key (idstage) references stages_proect;
alter table link_stage_proect add constraint FKck7er41uc1rqc28wixj6d3koc foreign key (idtask) references tasktab;
alter table proect add constraint FKsbj6w06ypup2wvadxognknla5 foreign key (idsost) references statetask;
alter table stages_proect add constraint FKqkas84kc2c0syh5e3xh1nsoh4 foreign key (idproect) references proect;
alter table stages_proect add constraint FKi5t0cbd3x8cyphljycdvhq16l foreign key (idsost) references statetask;
alter table task_user add constraint FK7w9foy29vk0w6t9nafmhqcm3u foreign key (idtask) references tasktab;
alter table task_user add constraint FKhgreb8w3xhjqs73nvb6w495ao foreign key (iduser) references app_user;
alter table tasktab add constraint FKfp20nqitj9xb4cf0c19kf3dkl foreign key (directortask) references app_user;
alter table tasktab add constraint FKpmalev9ukipjd21jb6yh96qvi foreign key (state) references statetask;
alter table tasktab add constraint FK9qjbdaogu1haa1jhcb34gf9yr foreign key (typetask) references typetask;
alter table User_Role add constraint FK3tdtqg65e5n3wvj1w2lga3r foreign key (Role_Id) references App_Role;
alter table User_Role add constraint FKiifkjb98bm76mqc1p6lmibs5o foreign key (User_Id) references app_user;
alter table users_proect add constraint FKbedjskyxhg3gjgaomm98n9r1p foreign key (idposition) references project_positions;
alter table users_proect add constraint FKra0o7ico2n0ikob3os5lq3dqh foreign key (idproect) references proect;
alter table users_proect add constraint FKnfdqf22iwfdukqcglqxy0grpl foreign key (iduser) references app_user;
alter table coment_task drop constraint FKlwhs34s6ems1ciko0p5qyp03w;
alter table coment_task drop constraint FKa3voby7ppkwporapfe47ltl27;
alter table inform_user_coment drop constraint FKl9c189233wodsa51p9e4y6vk0;
alter table inform_user_coment drop constraint FKp7m6u0olidslu8h4hkqb12or0;
alter table link_stage_proect drop constraint FKqbjt65fph8gox43sgdqt4a5mk;
alter table link_stage_proect drop constraint FKck7er41uc1rqc28wixj6d3koc;
alter table proect drop constraint FKsbj6w06ypup2wvadxognknla5;
alter table stages_proect drop constraint FKqkas84kc2c0syh5e3xh1nsoh4;
alter table stages_proect drop constraint FKi5t0cbd3x8cyphljycdvhq16l;
alter table task_user drop constraint FK7w9foy29vk0w6t9nafmhqcm3u;
alter table task_user drop constraint FKhgreb8w3xhjqs73nvb6w495ao;
alter table tasktab drop constraint FKfp20nqitj9xb4cf0c19kf3dkl;
alter table tasktab drop constraint FKpmalev9ukipjd21jb6yh96qvi;
alter table tasktab drop constraint FK9qjbdaogu1haa1jhcb34gf9yr;
alter table User_Role drop constraint FK3tdtqg65e5n3wvj1w2lga3r;
alter table User_Role drop constraint FKiifkjb98bm76mqc1p6lmibs5o;
alter table users_proect drop constraint FKbedjskyxhg3gjgaomm98n9r1p;
alter table users_proect drop constraint FKra0o7ico2n0ikob3os5lq3dqh;
alter table users_proect drop constraint FKnfdqf22iwfdukqcglqxy0grpl;
drop table if exists App_Role cascade;
drop table if exists app_user cascade;
drop table if exists coment_task cascade;
drop table if exists inform_user_coment cascade;
drop table if exists link_stage_proect cascade;
drop table if exists proect cascade;
drop table if exists project_positions cascade;
drop table if exists stages_proect cascade;
drop table if exists statetask cascade;
drop table if exists task_user cascade;
drop table if exists tasktab cascade;
drop table if exists typetask cascade;
drop table if exists User_Role cascade;
drop table if exists users_proect cascade;
drop sequence if exists customer_approle;
drop sequence if exists customer_appuser;
drop sequence if exists customer_comenttask;
drop sequence if exists customer_inf_user_coment;
drop sequence if exists customer_link_stage_proect;
drop sequence if exists customer_proect;
drop sequence if exists customer_project_position;
drop sequence if exists customer_stages_proect;
drop sequence if exists customer_state_task;
drop sequence if exists customer_task_user;
drop sequence if exists customer_tasktab;
drop sequence if exists customer_type_task;
drop sequence if exists customer_user_proect;
drop sequence if exists customer_userrole;
create sequence customer_approle start 1 increment 1;
create sequence customer_appuser start 1 increment 1;
create sequence customer_comenttask start 1 increment 1;
create sequence customer_inf_user_coment start 1 increment 1;
create sequence customer_link_stage_proect start 1 increment 1;
create sequence customer_proect start 1 increment 1;
create sequence customer_project_position start 1 increment 1;
create sequence customer_stages_proect start 1 increment 1;
create sequence customer_state_task start 1 increment 1;
create sequence customer_task_user start 1 increment 1;
create sequence customer_tasktab start 1 increment 1;
create sequence customer_type_task start 1 increment 1;
create sequence customer_user_proect start 1 increment 1;
create sequence customer_userrole start 1 increment 1;
create table App_Role (Role_Id int8 not null, Role_Name varchar(30) not null, primary key (Role_Id));
create table app_user (user_id int8 not null, enabled int4 not null, encryted_password varchar(255) not null, user_name varchar(255) not null, primary key (user_id));
create table coment_task (id int8 not null, countsled int4, datecoment date, textcoment varchar(255), idtask int8, usercoment int8, primary key (id));
create table inform_user_coment (id int8 not null, text varchar(255), idtask int8, iduser int8, primary key (id));
create table link_stage_proect (id int8 not null, idstage int8, idtask int8, primary key (id));
create table proect (id int8 not null, dateend timestamp, daterun timestamp, description varchar(255), name varchar(255), readiness int4, idsost int8, primary key (id));
create table project_positions (id int8 not null, name varchar(255), primary key (id));
create table stages_proect (id int8 not null, dateend timestamp, daterun timestamp, description varchar(255), name varchar(255), readiness int4, idproect int8, idsost int8, primary key (id));
create table statetask (id int8 not null, name varchar(255) not null, primary key (id));
create table task_user (id int8 not null, idtask int8, iduser int8, primary key (id));
create table tasktab (id int8 not null, description varchar(255), enddate timestamp, evaluation float8, modeldate timestamp, name varchar(255), startdate timestamp, directortask int8, state int8, typetask int8, primary key (id));
create table typetask (id int8 not null, name varchar(255) not null, primary key (id));
create table User_Role (Id int8 not null, Role_Id int8, User_Id int8, primary key (Id));
create table users_proect (id int8 not null, idposition int8, idproect int8, iduser int8, primary key (id));
alter table App_Role add constraint APP_ROLE_UK unique (Role_Name);
alter table User_Role add constraint USER_ROLE_UK unique (User_Id, Role_Id);
alter table coment_task add constraint FKlwhs34s6ems1ciko0p5qyp03w foreign key (idtask) references tasktab;
alter table coment_task add constraint FKa3voby7ppkwporapfe47ltl27 foreign key (usercoment) references app_user;
alter table inform_user_coment add constraint FKl9c189233wodsa51p9e4y6vk0 foreign key (idtask) references coment_task;
alter table inform_user_coment add constraint FKp7m6u0olidslu8h4hkqb12or0 foreign key (iduser) references app_user;
alter table link_stage_proect add constraint FKqbjt65fph8gox43sgdqt4a5mk foreign key (idstage) references stages_proect;
alter table link_stage_proect add constraint FKck7er41uc1rqc28wixj6d3koc foreign key (idtask) references tasktab;
alter table proect add constraint FKsbj6w06ypup2wvadxognknla5 foreign key (idsost) references statetask;
alter table stages_proect add constraint FKqkas84kc2c0syh5e3xh1nsoh4 foreign key (idproect) references proect;
alter table stages_proect add constraint FKi5t0cbd3x8cyphljycdvhq16l foreign key (idsost) references statetask;
alter table task_user add constraint FK7w9foy29vk0w6t9nafmhqcm3u foreign key (idtask) references tasktab;
alter table task_user add constraint FKhgreb8w3xhjqs73nvb6w495ao foreign key (iduser) references app_user;
alter table tasktab add constraint FKfp20nqitj9xb4cf0c19kf3dkl foreign key (directortask) references app_user;
alter table tasktab add constraint FKpmalev9ukipjd21jb6yh96qvi foreign key (state) references statetask;
alter table tasktab add constraint FK9qjbdaogu1haa1jhcb34gf9yr foreign key (typetask) references typetask;
alter table User_Role add constraint FK3tdtqg65e5n3wvj1w2lga3r foreign key (Role_Id) references App_Role;
alter table User_Role add constraint FKiifkjb98bm76mqc1p6lmibs5o foreign key (User_Id) references app_user;
alter table users_proect add constraint FKbedjskyxhg3gjgaomm98n9r1p foreign key (idposition) references project_positions;
alter table users_proect add constraint FKra0o7ico2n0ikob3os5lq3dqh foreign key (idproect) references proect;
alter table users_proect add constraint FKnfdqf22iwfdukqcglqxy0grpl foreign key (iduser) references app_user;
